### ISSUE TITLE
配置运行成功，但是实际没生效的话，应该怎么去排查是什么原因导致的？demo源码路径 spring-cloud-alibaba-examples/governance-example/label-routing-example

### ISSUE THREAD

**Issue by jmic134** [opensergo/opensergo-control-plane#50]
## Issue Description

Type: *feature request*

### Additional context
![8b7a21767d91b89e40c9c56d1e3dc1a](https://user-images.githubusercontent.com/11657445/212870766-e6b54728-8a5f-4b01-be07-e2c08fbe0fd7.jpg)
![8a456d39174b2a7a9fc73efea2434f8](https://user-images.githubusercontent.com/11657445/212870801-8091d23c-e69e-4eb4-a41f-51f4e2945112.jpg)
![image](https://user-images.githubusercontent.com/11657445/212871215-b04c7e62-0eef-413f-a496-02c383ff6d32.png)
![image](https://user-images.githubusercontent.com/11657445/212871325-c08a4843-b0ba-4fc0-a9cd-9b697b897a5e.png)

![image](https://user-images.githubusercontent.com/11657445/212871002-c2a30edc-43ce-48e5-a4db-886f4b0476e8.png)

**Comment by jnan806** [comment]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/43714056/212884246-53d7b2a8-0728-4b01-b9ce-5311bb35ef31.png">  


According to you screenshots, I get that, your test case is between develop environment and OpenSergo Control Plane in Kubernetes Cluster， so is your develop environment in one node of the Kubernetes Cluster? If not, you should expose the Service by change the Service type to LoadBalancer or NodePort for you test case.

---
从你的截图中，可以看出你是从开发环境与 Kubernetes Cluster 中的 OpenSergo Control Plane 进行通讯，所以你的开发环境是 Kubernetes Cluster 的一个节点吗？ 如果不是的话，需要将 Service 暴露出来，因为 Service 默认是 ClusterIP，你可以改为 LoadBalancer 或者 NodePort 进行测试。

https://opensergo.io/zh-cn/docs/quick-start/opensergo-control-plane/#注意事项

**Comment by jmic134** [comment]
感谢，已按照建议成功运行。
